os: linux

dist: xenial

sudo: false

language: java

jdk:
  oraclejdk11

cache:
  directories:
    - $HOME/.m2

install: true

script: expr $TRAVIS_BRANCH = master

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: target/*.zip
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_BRANCH = master